export {
  getElementsByTagName,
  getElementsByTagType,
  getElementById,
  findOne,
  findAll,
  getChildren,
  getParent,
  getSiblings,
  nextElementSibling,
  prevElementSibling,
  getName,
  getAttributeValue,
  hasAttrib,
  getText,
  textContent,
  innerText,
  getInnerHTML,
  getOuterHTML,
} from 'domutils'
